apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart
  namespace: default
  labels:
    app: cart
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cart
  template:
    metadata:
      labels:
        app: cart
    spec:
      containers:
      - name: cart
        image: cart:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 7001
          name: http
        env:
        - name: PORT
          value: "7001"
        - name: PRODUCT_CATALOG_SERVICE_ADDR
          value: "http://productcatalog:7000"
        - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
          value: "http://otel-collector:4317"
        - name: OTEL_EXPORTER_OTLP_METRICS_ENDPOINT
          value: "http://otel-collector:4317"
        - name: OTEL_SERVICE_NAME
          value: "cart"
        - name: OTEL_SERVICE_VERSION
          value: "1.0.0"
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: "service.name=cart,service.version=1.0.0"
        livenessProbe:
          httpGet:
            path: /health
            port: 7001
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: 7001
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: cart
  namespace: default
  labels:
    app: cart
spec:
  selector:
    app: cart
  ports:
  - name: http
    port: 7001
    targetPort: 7001
    protocol: TCP
  type: ClusterIP

