apiVersion: apps/v1
kind: Deployment
metadata:
  name: productcatalog
  namespace: default
  labels:
    app: productcatalog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: productcatalog
  template:
    metadata:
      labels:
        app: productcatalog
    spec:
      containers:
      - name: productcatalog
        image: productcatalog:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 7000
          name: http
        env:
        - name: PORT
          value: "7000"
        - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
          value: "http://otel-collector:4317"
        - name: OTEL_EXPORTER_OTLP_METRICS_ENDPOINT
          value: "http://otel-collector:4317"
        - name: OTEL_SERVICE_NAME
          value: "productcatalog"
        - name: OTEL_SERVICE_VERSION
          value: "1.0.0"
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: "service.name=productcatalog,service.version=1.0.0"
        livenessProbe:
          httpGet:
            path: /health
            port: 7000
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: 7000
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: productcatalog
  namespace: default
  labels:
    app: productcatalog
spec:
  selector:
    app: productcatalog
  ports:
  - name: http
    port: 7000
    targetPort: 7000
    protocol: TCP
  type: ClusterIP

